mapBase = {
  "version": 8,
  "name": "MapaBaseRioja_SCN_Color",
  "metadata": {"maputnik:renderer": "mbgljs"},
  "sources": {
    "VTS_MapaBaseRioja_SCN": {
      "type": "vector",
      "tiles": ["https://www.ign.es/web/resources/mapa-base-xyz/vt/{z}/{x}/{y}.pbf"],
      "minZoom": 0,
      "maxZoom": 13
    }
  },
  "sprite": "https://vts.larioja.org/sprite/sprite",
  "glyphs": "https://vts.larioja.org/font/{fontstack}/{range}.pbf",
  "layers": [
    {
      "id": "fondo",
      "type": "background",
      "layout": {"visibility": "visible"},
      "paint": {"background-color": "rgba(201, 201, 201, 1)"}
    },
    {
      "id": "comunidad_autonoma_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "5-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "comunidad_autonoma_pol",
      "minzoom": 5,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(255, 255, 255, 1)"}
    },
    {
      "id": "provincia_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "7-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "provincia_pol",
      "minzoom": 7,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(255, 255, 255, 1)"}
    },
    {
      "id": "municipio_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "9-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "municipio_pol",
      "minzoom": 9,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(255, 255, 255, 1)"}
    },
    {
      "id": "tierra_firme_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "0-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "tierra_firme_pol",
      "minzoom": 0,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(249, 244, 232, 1)"}
    },
    {
      "id": "cubierta_vegetal_pol-todos",
      "type": "fill",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "cubierta_vegetal_pol",
      "minzoom": 15,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(219, 234, 210, 1)"}
    },
    {
      "id": "cubierta_vegetal_pol-coniferas_frondosas_mixto",
      "type": "fill",
      "metadata": {"maputnik:comment": "13-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "cubierta_vegetal_pol",
      "minzoom": 13,
      "maxzoom": 22,
      "filter": [
        "any",
        ["==", "clase", "bosque_coniferas"],
        ["==", "clase", "bosque_frondosas"],
        ["==", "clase", "bosque mixto"]
      ],
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(219, 234, 210, 1)"}
    },
    {
      "id": "cubierta_vegetal_bosque_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "7-13"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "cubierta_vegetal_bosque_pol",
      "minzoom": 7,
      "maxzoom": 13,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(219, 234, 210, 1)"}
    },
    {
      "id": "espacio_natural_protegido_pol-todos",
      "type": "fill",
      "metadata": {"maputnik:comment": "11-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "espacio_natural_protegido_pol",
      "minzoom": 11,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(219, 234, 210, 1)"}
    },
    {
      "id": "espacio_natural_protegido_pol-parquenatural_humedal",
      "type": "fill",
      "metadata": {"maputnik:comment": "9-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "espacio_natural_protegido_pol",
      "minzoom": 9,
      "maxzoom": 22,
      "filter": [
        "any",
        ["==", "clase", "parque_natural"],
        ["==", "clase", "humedal_protegido"],
        [
          "==",
          "clase",
          "zona_de_especial_conservacion_de_importancia_comunitaria"
        ],
        ["==", "clase", "zona_de_importancia_comunitaria_lic"],
        ["==", "clase", "zona_de_la_red_ecologica_europea_natura_2000"]
      ],
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(219, 234, 210, 1)"}
    },
    {
      "id": "espacio_natural_protegido_pol-parquenacional_reservabiosfera",
      "type": "fill",
      "metadata": {"maputnik:comment": "7-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "espacio_natural_protegido_pol",
      "minzoom": 7,
      "maxzoom": 22,
      "filter": [
        "any",
        ["==", "clase", "parque_nacional"],
        ["==", "clase", "reserva_de_la_biosfera"]
      ],
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(219, 234, 210, 1)"}
    },
    {
      "id": "espacio_natural_protegido_pol-contorno",
      "type": "line",
      "metadata": {"maputnik:comment": "7-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "espacio_natural_protegido_pol",
      "minzoom": 7,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(39, 61, 26, 1)",
        "line-opacity": 0.5,
        "line-width": 1,
        "line-dasharray": [3, 3]
      }
    },
    {
      "id": "nucleo_urbano_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "10-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nucleo_urbano_pol",
      "minzoom": 10,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(230, 230, 230, 1)", "fill-opacity": 0.5}
    },
    {
      "id": "manzana_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "manzana_pol",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(230, 230, 230, 1)"}
    },
    {
      "id": "zona_dotacional_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "13-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "zona_dotacional_pol",
      "minzoom": 13,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(236, 215, 198, 1)"}
    },
    {
      "id": "zona_militar_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "zona_militar_pol",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(243, 227, 221, 1)"}
    },
    {
      "id": "zona_industrial_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "zona_industrial_pol",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(232, 222, 255, 1)"}
    },
    {
      "id": "zona_protegida_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "zona_protegida_pol",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(152, 166, 143, 1)"}
    },
    {
      "id": "zona_verde_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "13-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "zona_verde_pol",
      "minzoom": 13,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(219, 234, 210, 1)"}
    },
    {
      "id": "instalacion_deportiva_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_deportiva_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(217, 228, 204, 1)"}
    },
    {
      "id": "instalacion_educativa_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_educativa_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(236, 215, 198, 1)"}
    },
    {
      "id": "instalacion_energia_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_energia_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-opacity": 1, "fill-color": "rgba(177, 181, 181, 0.73)"}
    },
    {
      "id": "instalacion_militar_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_militar_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(243, 227, 221, 1)"}
    },
    {
      "id": "instalacion_sanitaria_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_sanitaria_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(243, 236, 196, 1)"}
    },
    {
      "id": "instalacion_telecomunicacion_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_telecomunicacion_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(204, 204, 202, 1)"}
    },
    {
      "id": "instalacion_tratamiento_aguas_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_tratamiento_aguas_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(173, 182, 199, 1)"}
    },
    {
      "id": "instalacion_tratamiento_residuos_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_tratamiento_residuos_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(109, 101, 96, 1)"}
    },
    {
      "id": "area_servicio_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "area_servicio_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(233, 225, 220, 1)"}
    },
    {
      "id": "peaje_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "peaje_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(233, 225, 220, 1)"}
    },
    {
      "id": "aparcamiento_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "aparcamiento_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(233, 225, 220, 1)"}
    },
    {
      "id": "puerto_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "puerto_pol",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(189, 186, 189, 1)"}
    },
    {
      "id": "aerodromo_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "aerodromo_pol",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(189, 186, 189, 1)"}
    },
    {
      "id": "estacion_autobus_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "estacion_autobus_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(233, 225, 220, 1)"}
    },
    {
      "id": "estacion_ferrocarril_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "estacion_ferrocarril_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(233, 225, 220, 1)"}
    },
    {
      "id": "lamina_agua_pol-todos",
      "type": "fill",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "lamina_agua_pol",
      "minzoom": 15,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(177, 209, 228, 1)"}
    },
    {
      "id": "lamina_agua_pol-balsa_lago",
      "type": "fill",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "lamina_agua_pol",
      "minzoom": 12,
      "maxzoom": 22,
      "filter": [
        "any",
        ["==", "clase", "balsa_alberca"],
        ["==", "clase", "lago"]
      ],
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(177, 209, 228, 1)"}
    },
    {
      "id": "lamina_agua_pol-embalse_marisma",
      "type": "fill",
      "metadata": {"maputnik:comment": "8-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "lamina_agua_pol",
      "minzoom": 8,
      "maxzoom": 22,
      "filter": ["any", ["==", "clase", "embalse"], ["==", "clase", "marisma"]],
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(177, 209, 228, 1)"}
    },
    {
      "id": "hidrografia_pol",
      "type": "line",
      "metadata": {"maputnik:comment": "9-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "hidrografia_pol",
      "minzoom": 11,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"line-color": "rgba(146, 204, 243, 1)"}
    },
    {
      "id": "hidrografia_lin-todos",
      "type": "line",
      "metadata": {"maputnik:comment": "10-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "hidrografia_lin",
      "minzoom": 10,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"line-color": "rgba(146, 204, 243, 1)", "line-width": 0.7}
    },
    {
      "id": "hidrografia_lin-orden3-4",
      "type": "line",
      "metadata": {"maputnik:comment": "9-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "hidrografia_lin",
      "minzoom": 9,
      "maxzoom": 22,
      "filter": ["all", ["==", "orden", "tercero_cuarto"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(146, 204, 243, 1)",
        "line-width": {"stops": [[9, 0.7], [10, 1]]}
      }
    },
    {
      "id": "hidrografia_lin-orden2",
      "type": "line",
      "metadata": {"maputnik:comment": "8-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "hidrografia_lin",
      "minzoom": 8,
      "maxzoom": 22,
      "filter": ["all", ["==", "orden", "segundo"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(146, 204, 243, 1)",
        "line-width": {"stops": [[8, 0.7], [9, 1], [10, 1.2]]}
      }
    },
    {
      "id": "hidrografia_lin-orden1",
      "type": "line",
      "metadata": {"maputnik:comment": "7-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "hidrografia_lin",
      "minzoom": 7,
      "maxzoom": 22,
      "filter": ["all", ["==", "orden", "primero"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(146, 204, 243, 1)",
        "line-width": {"stops": [[7, 0.7], [8, 1], [9, 1.2], [10, 1.5]]}
      }
    },
    {
      "id": "conduccion_lin-todos",
      "type": "line",
      "metadata": {"maputnik:comment": "16-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "conduccion_lin",
      "minzoom": 16,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(0, 0, 0, 1)",
        "line-width": 0.3,
        "line-dasharray": [15, 3]
      }
    },
    {
      "id": "conduccion_lin-energia_gas_combustible",
      "type": "line",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "conduccion_lin",
      "minzoom": 14,
      "maxzoom": 22,
      "filter": [
        "any",
        ["==", "clase", "conduccion_energia"],
        ["==", "clase", "conduccion_gas"],
        ["==", "clase", "conduccion_combustible"]
      ],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(0, 0, 0, 1)",
        "line-width": 0.3,
        "line-dasharray": [15, 3]
      }
    },
    {
      "id": "ruta_lin",
      "type": "line",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "ruta_lin",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(136, 90, 90, 1)",
        "line-opacity": 0.7,
        "line-width": {"stops": [[14, 0.5], [16, 0.7]]},
        "line-dasharray": [3, 3]
      }
    },
    {
      "id": "senda_lin",
      "type": "line",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "senda_lin",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(136, 90, 90, 1)",
        "line-opacity": 0.7,
        "line-width": {"stops": [[14, 0.5], [16, 0.7]]},
        "line-dasharray": [3, 3]
      }
    },
    {
      "id": "camino_lin",
      "type": "line",
      "metadata": {"maputnik:comment": "13-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "camino_lin",
      "minzoom": 13,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(136, 90, 90, 1)",
        "line-opacity": 0.7,
        "line-width": {"stops": [[13, 0.5], [16, 0.7]]}
      }
    },
    {
      "id": "via_servicio_lin",
      "type": "line",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "via_servicio_lin",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"line-color": "rgba(162, 162, 162, 1)", "line-width": 0.2}
    },
    {
      "id": "via_urbana_lin-gris",
      "type": "line",
      "metadata": {"maputnik:comment": "13-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "via_urbana_lin",
      "minzoom": 13,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"line-color": "rgba(162, 162, 162, 1)", "line-width": 0.3}
    },
    {
      "id": "via_urbana_lin-blanco",
      "type": "line",
      "metadata": {"maputnik:comment": "16-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "via_urbana_lin",
      "minzoom": 16,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(255, 255, 255, 1)",
        "line-width": {"stops": [[16, 2], [18, 6]]}
      }
    },
    {
      "id": "carretera_otros_lin",
      "type": "line",
      "metadata": {"maputnik:comment": "11-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_otros_lin",
      "minzoom": 11,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"line-color": "rgba(231, 23, 23, 1)", "line-width": 0.5}
    },
    {
      "id": "carretera_autonomica_3er_nivel_lin-contorno",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_autonomica_3er_nivel_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(0, 0, 0, 1)",
        "line-width": {"stops": [[15, 3], [18, 5]]},
        "line-opacity": 0.7
      }
    },
    {
      "id": "carretera_autonomica_3er_nivel_lin-relleno",
      "type": "line",
      "metadata": {"maputnik:comment": "10-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_autonomica_3er_nivel_lin",
      "minzoom": 10,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(255, 220, 0, 1)",
        "line-width": {"stops": [[10, 1.2], [11, 1.5], [13, 2], [15, 3]]},
        "line-opacity": 0.7
      }
    },
    {
      "id": "carretera_autonomica_2do_nivel_lin-contorno",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_autonomica_2do_nivel_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(0, 0, 0, 1)",
        "line-width": {"stops": [[15, 3], [18, 5]]},
        "line-opacity": 0.7
      }
    },
    {
      "id": "carretera_autonomica_2do_nivel_lin-relleno",
      "type": "line",
      "metadata": {"maputnik:comment": "9-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_autonomica_2do_nivel_lin",
      "minzoom": 9,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(0, 153, 0, 1)",
        "line-width": {
          "stops": [[9, 0.8], [10, 1.2], [11, 1.5], [13, 2], [15, 3]]
        },
        "line-opacity": 0.7
      }
    },
    {
      "id": "carretera_autonomica_1er_nivel_lin-contorno",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_autonomica_1er_nivel_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-width": {"stops": [[15, 3], [18, 5]]},
        "line-color": "rgba(0, 0, 0, 1)",
        "line-opacity": 0.7
      }
    },
    {
      "id": "carretera_autonomica_1er_nivel_lin-relleno",
      "type": "line",
      "metadata": {"maputnik:comment": "8-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_autonomica_1er_nivel_lin",
      "minzoom": 8,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-width": {
          "stops": [[8, 0.6], [9, 0.8], [10, 1.2], [11, 1.5], [13, 2], [15, 3]]
        },
        "line-color": "rgba(255, 153, 0, 1)",
        "line-opacity": 0.7
      }
    },
    {
      "id": "carretera_general_lin-contorno",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_general_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(148, 61, 61, 1)",
        "line-width": {"stops": [[15, 3], [18, 5]]},
        "line-opacity": 0.7
      }
    },
    {
      "id": "carretera_general_lin-relleno",
      "type": "line",
      "metadata": {"maputnik:comment": "7-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_general_lin",
      "minzoom": 7,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-opacity": 0.7,
        "line-color": "rgba(231, 23, 23, 1)",
        "line-width": {
          "stops": [
            [7, 0.4],
            [8, 0.6],
            [9, 0.8],
            [10, 1.2],
            [11, 1.5],
            [13, 2],
            [15, 3]
          ]
        }
      }
    },
    {
      "id": "carretera_general_lin-puente",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_general_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "filter": ["all", ["==", "puente", "T"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(246, 170, 170, 1)",
        "line-width": 2,
        "line-opacity": 0.7
      }
    },
    {
      "id": "carretera_general_lin-tunel",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_general_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "filter": ["all", ["==", "tunel", "T"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(95, 39, 38, 1)",
        "line-width": 4,
        "line-opacity": 0.5
      }
    },
    {
      "id": "autopista_lin-contorno",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autopista_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(96, 71, 58, 1)",
        "line-width": {"stops": [[15, 6], [18, 7]]},
        "line-opacity": 0.7
      }
    },
    {
      "id": "autopista_lin-relleno",
      "type": "line",
      "metadata": {"maputnik:comment": "6-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autopista_lin",
      "minzoom": 6,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": {
          "stops": [[6, "rgba(200, 146, 2, 1)"], [15, "rgba(248, 200, 68, 1)"]]
        },
        "line-width": {"stops": [[6, 1], [11, 2], [15, 3], [18, 5]]},
        "line-opacity": 0.7
      }
    },
    {
      "id": "autopista_lin-puente_contorno",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autopista_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "filter": ["all", ["==", "puente", "T"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(127, 83, 55, 1)",
        "line-width": {"stops": [[15, 7], [18, 9]]},
        "line-opacity": 0.7,
        "line-dasharray": [2, 2]
      }
    },
    {
      "id": "autopista_lin-puente_relleno",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autopista_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "filter": ["all", ["==", "puente", "T"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(251, 230, 170, 1)",
        "line-width": {"stops": [[15, 3], [18, 5]]},
        "line-opacity": 0.7
      }
    },
    {
      "id": "autopista_lin-tunel",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autopista_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "filter": ["all", ["==", "tunel", "T"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(78, 61, 10, 1)",
        "line-width": {"stops": [[15, 3], [18, 5]]},
        "line-opacity": 0.5
      }
    },
    {
      "id": "autovia_lin-contorno",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autovia_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(96, 71, 58, 1)",
        "line-width": {"stops": [[15, 6], [18, 7]]},
        "line-opacity": 0.7
      }
    },
    {
      "id": "autovia_lin-relleno",
      "type": "line",
      "metadata": {"maputnik:comment": "6-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autovia_lin",
      "minzoom": 6,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": {
          "stops": [[6, "rgba(200, 146, 2, 1)"], [15, "rgba(248, 200, 68, 1)"]]
        },
        "line-width": {"stops": [[6, 1], [11, 2], [15, 3], [18, 5]]},
        "line-opacity": 0.7
      }
    },
    {
      "id": "autovia_lin-puente_contorno",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autovia_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "filter": ["all", ["==", "puente", "T"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-width": {"stops": [[15, 7], [18, 9]]},
        "line-opacity": 0.7,
        "line-dasharray": [2, 2],
        "line-color": "rgba(127, 83, 55, 1)"
      }
    },
    {
      "id": "autovia_lin-puente_relleno",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autovia_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "filter": ["all", ["==", "puente", "T"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(251, 230, 170, 1)",
        "line-width": {"stops": [[15, 3], [18, 5]]},
        "line-opacity": 0.7
      }
    },
    {
      "id": "autovia_lin-tunel",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autovia_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "filter": ["all", ["==", "tunel", "T"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(78, 61, 10, 1)",
        "line-width": {"stops": [[15, 3], [18, 5]]},
        "line-opacity": 0.5
      }
    },
    {
      "id": "ferrocarril_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "13-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "ferrocarril_pol",
      "minzoom": 13,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"fill-color": "rgba(177, 177, 177, 1)"}
    },
    {
      "id": "ferrocarril_lin-todos_continuo",
      "type": "line",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "ferrocarril_lin",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(59, 59, 59, 1)",
        "line-width": {"stops": [[12, 2], [15, 3.5]]}
      }
    },
    {
      "id": "ferrocarril_lin-tren_continuo",
      "type": "line",
      "metadata": {"maputnik:comment": "7-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "ferrocarril_lin",
      "minzoom": 7,
      "maxzoom": 22,
      "filter": ["all", ["==", "clase", "tren"]],
      "layout": {"visibility": "visible"},
      "paint": {"line-color": "rgba(59, 59, 59, 1)", "line-width": 0.8}
    },
    {
      "id": "ferrocarril_lin-todos_discontinuo",
      "type": "line",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "ferrocarril_lin",
      "minzoom": 12,
      "maxzoom": 22,
      "filter": ["all", ["==", "clase", "tren"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(254, 254, 254, 1)",
        "line-width": 2,
        "line-dasharray": [3, 3]
      }
    },
    {
      "id": "altimetria_lin-todos",
      "type": "line",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "altimetria_lin",
      "minzoom": 15,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {"line-color": "rgba(235, 169, 169, 0.5)", "line-width": 0.3}
    },
    {
      "id": "altimetria_lin-05",
      "type": "line",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "altimetria_lin",
      "minzoom": 14,
      "maxzoom": 22,
      "filter": [
        "all",
        [
          "in",
          "altitud",
          0,
          5,
          10,
          15,
          20,
          25,
          30,
          35,
          40,
          45,
          50,
          55,
          60,
          65,
          70,
          75,
          80,
          85,
          90,
          95,
          100,
          105,
          110,
          115,
          120,
          125,
          130,
          135,
          140,
          145,
          150,
          155,
          160,
          165,
          170,
          175,
          180,
          185,
          190,
          195,
          200,
          205,
          210,
          215,
          220,
          225,
          230,
          235,
          240,
          245,
          250,
          255,
          260,
          265,
          270,
          275,
          280,
          285,
          290,
          295,
          300,
          305,
          310,
          315,
          320,
          325,
          330,
          335,
          340,
          345,
          350,
          355,
          360,
          365,
          370,
          375,
          380,
          385,
          390,
          395,
          400,
          405,
          410,
          415,
          420,
          425,
          430,
          435,
          440,
          445,
          450,
          455,
          460,
          465,
          470,
          475,
          480,
          485,
          490,
          495,
          500,
          505,
          510,
          515,
          120,
          525,
          530,
          535,
          540,
          545,
          550,
          555,
          560,
          565,
          570,
          575,
          580,
          585,
          590,
          596,
          600,
          605,
          610,
          615,
          620,
          625,
          630,
          635,
          640,
          645,
          650,
          655,
          660,
          665,
          670,
          675,
          680,
          685,
          690,
          695,
          700,
          705,
          710,
          715,
          720,
          725,
          730,
          735,
          740,
          745,
          750,
          755,
          760,
          765,
          770,
          775,
          780,
          785,
          790,
          795,
          800,
          805,
          810,
          815,
          820,
          825,
          830,
          835,
          840,
          845,
          850,
          855,
          860,
          865,
          870,
          875,
          880,
          885,
          890,
          895,
          900,
          905,
          910,
          915,
          920,
          925,
          930,
          935,
          940,
          945,
          950,
          955,
          960,
          965,
          970,
          975,
          980,
          985,
          990,
          995,
          1000,
          1005,
          1010,
          1015,
          1020,
          1025,
          1030,
          1035,
          1040,
          1045,
          1050,
          1055,
          1060,
          1065,
          1070,
          1075,
          1080,
          1085,
          1090,
          1095,
          1100,
          1105,
          1110,
          1115,
          1120,
          1125,
          1130,
          1135,
          1140,
          1145,
          1150,
          1155,
          1160,
          1165,
          1170,
          1175,
          1180,
          1185,
          1190,
          1195,
          1200,
          1205,
          1210,
          1215,
          1220,
          1225,
          1230,
          1235,
          1240,
          1245,
          1250,
          1255,
          1260,
          1265,
          1270,
          1275,
          1280,
          1285,
          1290,
          1295,
          1300,
          1305,
          1310,
          1315,
          1320,
          1325,
          1330,
          1335,
          1340,
          1345,
          1350,
          1355,
          1360,
          1365,
          1370,
          1375,
          1380,
          1385,
          1390,
          1395,
          1400,
          1405,
          1410,
          1415,
          1420,
          1425,
          1430,
          1435,
          1440,
          1445,
          1450,
          1455,
          1460,
          1465,
          1470,
          1475,
          1480,
          1485,
          1490,
          1495,
          1500,
          1505,
          1510,
          1515,
          1520,
          1525,
          1530,
          1535,
          1540,
          1545,
          1550,
          1555,
          1560,
          1565,
          1570,
          1575,
          1580,
          1585,
          1590,
          1595,
          1600,
          1605,
          1610,
          1615,
          1620,
          1625,
          1630,
          1635,
          1640,
          1645,
          1650,
          1655,
          1660,
          1665,
          1670,
          1675,
          1680,
          1685,
          1690,
          1695,
          1700,
          1705,
          1710,
          1715,
          1720,
          1725,
          1730,
          1735,
          1740,
          1745,
          1750,
          1755,
          1760,
          1765,
          1770,
          1775,
          1780,
          1785,
          1790,
          1795,
          1800,
          1805,
          1810,
          1815,
          1820,
          1825,
          1830,
          1835,
          1840,
          1845,
          1850,
          1855,
          1860,
          1865,
          1870,
          1875,
          1880,
          1885,
          1890,
          1895,
          1900,
          1905,
          1910,
          1915,
          1920,
          1925,
          1930,
          1935,
          1940,
          1945,
          1950,
          1955,
          1960,
          1965,
          1970,
          1975,
          1980,
          1985,
          1990,
          1995,
          2000,
          2005,
          2010,
          2015,
          2020,
          2025,
          2030,
          2035,
          2040,
          2045,
          2050,
          2055,
          2060,
          2065,
          2070,
          2075,
          2080,
          2085,
          2090,
          2095,
          2100,
          2105,
          2110,
          2115,
          2120,
          2125,
          2130,
          2135,
          2140,
          2145,
          2150,
          2155,
          2160,
          2165,
          2170,
          2175,
          2180,
          2185,
          2190,
          2195,
          2200,
          2205,
          2210,
          2215,
          2220,
          2225,
          2230,
          2235,
          2240,
          2245,
          2250,
          2255,
          2260,
          2265,
          2270,
          2275,
          2280,
          2285,
          2290,
          2295,
          2300
        ]
      ],
      "layout": {"visibility": "visible"},
      "paint": {"line-color": "rgba(234, 158, 44, 0.5)", "line-width": 0.3}
    },
    {
      "id": "altimetria_lin-25",
      "type": "line",
      "metadata": {"maputnik:comment": "13-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "altimetria_lin",
      "minzoom": 13,
      "maxzoom": 22,
      "filter": [
        "all",
        [
          "in",
          "altitud",
          0,
          25,
          50,
          75,
          100,
          125,
          150,
          175,
          200,
          225,
          250,
          275,
          300,
          325,
          350,
          375,
          400,
          425,
          450,
          475,
          500,
          525,
          550,
          575,
          600,
          625,
          650,
          675,
          700,
          725,
          750,
          775,
          800,
          825,
          850,
          875,
          900,
          925,
          950,
          975,
          1000,
          1025,
          1050,
          1055,
          1075,
          1100,
          1125,
          1150,
          1175,
          1200,
          1225,
          1250,
          1275,
          1300,
          1325,
          1350,
          1375,
          1400,
          1425,
          1450,
          1475,
          1500,
          1525,
          1550,
          1575,
          1600,
          1625,
          1650,
          1675,
          1700,
          1725,
          1750,
          1775,
          1800,
          1825,
          1850,
          1875,
          1900,
          1925,
          1950,
          1975,
          2000,
          2025,
          2050,
          2075,
          2100,
          2150,
          2175,
          2200,
          2225,
          2250,
          2275,
          2300
        ]
      ],
      "layout": {"visibility": "visible"},
      "paint": {"line-color": "rgba(153, 76, 0, 0.5)", "line-width": 0.3}
    },
    {
      "id": "altimetria_lin-50",
      "type": "line",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "altimetria_lin",
      "minzoom": 12,
      "maxzoom": 22,
      "filter": [
        "all",
        [
          "in",
          "altitud",
          50,
          100,
          150,
          200,
          250,
          300,
          350,
          400,
          450,
          500,
          550,
          600,
          650,
          700,
          750,
          800,
          850,
          900,
          950,
          1000,
          1050,
          1100,
          1150,
          1200,
          1250,
          1300,
          1350,
          1400,
          1450,
          1500,
          1550,
          1600,
          1650,
          1700,
          1750,
          1800,
          1850,
          1900,
          1950,
          2000,
          2050,
          2100,
          2150,
          2200,
          2250,
          2300
        ]
      ],
      "layout": {"visibility": "visible"},
      "paint": {"line-color": "rgba(153, 38, 0, 0.5)", "line-width": 0.3}
    },
    {
      "id": "linea_limite_lin-municipio",
      "type": "line",
      "metadata": {"maputnik:comment": "9-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "linea_limite_lin",
      "minzoom": 9,
      "maxzoom": 22,
      "filter": ["all", ["==", "clase", "limite_municipal"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(197, 197, 197, 1)",
        "line-width": 1,
        "line-dasharray": [3, 3]
      }
    },
    {
      "id": "linea_limite_lin-provincia",
      "type": "line",
      "metadata": {"maputnik:comment": "7-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "linea_limite_lin",
      "minzoom": 7,
      "maxzoom": 22,
      "filter": ["all", ["==", "clase", "limite_provincial"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(150, 150, 150, 1)",
        "line-width": {"stops": [[7, 0.3], [11, 2]]},
        "line-dasharray": [3, 3]
      }
    },
    {
      "id": "linea_limite_lin-ccaa",
      "type": "line",
      "metadata": {"maputnik:comment": "5-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "linea_limite_lin",
      "minzoom": 5,
      "maxzoom": 22,
      "filter": ["all", ["==", "clase", "limite_autonomico"]],
      "layout": {"visibility": "visible"},
      "paint": {
        "line-color": "rgba(150, 150, 150, 1)",
        "line-width": {"stops": [[5, 0.1], [7, 0.3], [11, 2]]},
        "line-dasharray": [3, 3]
      }
    },
    {
      "id": "construccion_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "16-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "construccion_pol",
      "minzoom": 16,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "fill-outline-color": "rgba(150, 143, 143, 1)",
        "fill-color": "rgba(221, 221, 221, 1)"
      }
    },
    {
      "id": "edificio_pol",
      "type": "fill",
      "metadata": {"maputnik:comment": "16-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "edificio_pol",
      "minzoom": 16,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "fill-color": "rgba(218, 216, 216, 1)",
        "fill-outline-color": "rgba(150, 143, 143, 1)"
      }
    },
    {
      "id": "nombre_hidrografia_pto-todos",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_hidrografia_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "visibility": "visible",
        "text-keep-upright": true,
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "symbol-placement": "point",
        "text-size": {"stops": [[14, 8], [15, 10], [16, 12]]}
      },
      "paint": {"text-color": "rgba(24, 124, 191, 1)"}
    },
    {
      "id": "nombre_hidrografia_pto-mar_isla",
      "type": "symbol",
      "metadata": {"maputnik:comment": "7-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_hidrografia_pto",
      "minzoom": 7,
      "maxzoom": 22,
      "filter": ["any", ["==", "clase", "mar"], ["==", "clase", "isla"]],
      "layout": {
        "text-anchor": "center",
        "visibility": "visible",
        "text-keep-upright": true,
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 12
      },
      "paint": {"text-color": "rgba(24, 124, 191, 1)"}
    },
    {
      "id": "nombre_hidrografia_pto-embalse_entrante_saliente",
      "type": "symbol",
      "metadata": {"maputnik:comment": "11-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_hidrografia_pto",
      "minzoom": 11,
      "maxzoom": 22,
      "filter": [
        "any",
        ["==", "clase", "embalse"],
        ["==", "clase", "entrante_costero_estrecho_maritimo"],
        ["==", "clase", "saliente_costero"]
      ],
      "layout": {
        "text-anchor": "center",
        "visibility": "visible",
        "text-keep-upright": true,
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 10
      },
      "paint": {"text-color": "rgba(24, 124, 191, 1)"}
    },
    {
      "id": "nombre_orografia_pto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "13-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_orografia_pto",
      "minzoom": 13,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 8], [15, 11], [17, 13]]},
        "visibility": "visible",
        "text-keep-upright": true
      },
      "paint": {
        "text-color": "rgba(99, 130, 115, 1)",
        "text-halo-width": 1,
        "text-halo-color": "rgba(255, 255, 255, 0.75)"
      }
    },
    {
      "id": "nombre_division_administrativa_pto-todos",
      "type": "symbol",
      "metadata": {"maputnik:comment": "10-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_division_administrativa_pto",
      "minzoom": 10,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 10,
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "uppercase"
      },
      "paint": {"text-color": "rgba(112, 112, 112, 1)"}
    },
    {
      "id": "nombre_division_administrativa_pto-nacion",
      "type": "symbol",
      "metadata": {"maputnik:comment": "3-5"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_division_administrativa_pto",
      "minzoom": 3,
      "maxzoom": 5,
      "filter": ["all", ["==", "clase", "nacion"]],
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 12,
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "uppercase"
      },
      "paint": {
        "text-color": "rgba(112, 112, 112, 1)",
        "text-halo-width": 1,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "nombre_division_administrativa_pto-ccaa",
      "type": "symbol",
      "metadata": {"maputnik:comment": "5-7"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_division_administrativa_pto",
      "minzoom": 5,
      "maxzoom": 7,
      "filter": [
        "any",
        ["==", "clase", "comunidad_autonoma"],
        ["==", "clase", "ciudad_autonoma"]
      ],
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 12,
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "uppercase"
      },
      "paint": {
        "text-color": "rgba(112, 112, 112, 1)",
        "text-halo-width": 1,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "nombre_division_administrativa_pto-provincia",
      "type": "symbol",
      "metadata": {"maputnik:comment": "7-9"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_division_administrativa_pto",
      "minzoom": 7,
      "maxzoom": 9,
      "filter": ["all", ["==", "clase", "provincia"]],
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 12,
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "uppercase"
      },
      "paint": {
        "text-color": "rgba(112, 112, 112, 1)",
        "text-halo-width": 1,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "nombre_division_administrativa_pto-municipio",
      "type": "symbol",
      "metadata": {"maputnik:comment": "9-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_division_administrativa_pto",
      "minzoom": 9,
      "maxzoom": 22,
      "filter": ["all", ["==", "clase", "municipio"]],
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 10,
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "uppercase"
      },
      "paint": {
        "text-color": "rgba(112, 112, 112, 1)",
        "text-halo-color": "rgba(177, 177, 177, 0)"
      }
    },
    {
      "id": "nombre_poblacion_construccion_pto-todos",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_poblacion_construccion_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Italic"],
        "text-size": 10,
        "visibility": "visible",
        "text-keep-upright": true
      },
      "paint": {
        "text-color": "rgba(101, 101, 101, 1)",
        "text-halo-width": 1,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "nombre_poblacion_construccion_pto-capitalestado",
      "type": "symbol",
      "metadata": {"maputnik:comment": "7-8"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_poblacion_construccion_pto",
      "minzoom": 7,
      "maxzoom": 8,
      "filter": ["all", ["==", "clase", "capital_estado"]],
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 18,
        "visibility": "visible",
        "text-keep-upright": true
      },
      "paint": {
        "text-color": "rgba(0, 0, 0, 0.75)",
        "text-halo-width": 1,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "nombre_poblacion_construccion_pto-capitalccaa",
      "type": "symbol",
      "metadata": {"maputnik:comment": "7-8"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_poblacion_construccion_pto",
      "minzoom": 7,
      "maxzoom": 8,
      "filter": [
        "all",
        ["==", "clase", "capital_comunidad_autonoma_ciudad_autonoma"]
      ],
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 12,
        "visibility": "visible",
        "text-keep-upright": true
      },
      "paint": {
        "text-color": "rgba(0, 0, 0, 0.75)",
        "text-halo-width": 1,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "nombre_poblacion_construccion_pto-capitalprovincia",
      "type": "symbol",
      "metadata": {"maputnik:comment": "8-9"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_poblacion_construccion_pto",
      "minzoom": 8,
      "maxzoom": 9,
      "filter": ["all", ["==", "clase", "capital_provincia"]],
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 12,
        "visibility": "visible",
        "text-keep-upright": true
      },
      "paint": {
        "text-color": "rgba(0, 0, 0, 0.75)",
        "text-halo-width": 1,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "nombre_poblacion_construccion_pto-municipio",
      "type": "symbol",
      "metadata": {"maputnik:comment": "9-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_poblacion_construccion_pto",
      "minzoom": 9,
      "maxzoom": 22,
      "filter": ["all", ["==", "clase", "capital_municipio"]],
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[10, 12], [12, 14]]},
        "visibility": "visible",
        "text-keep-upright": true
      },
      "paint": {
        "text-color": "rgba(101, 101, 101, 1)",
        "text-halo-width": 1,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "nombre_transporte_pto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "nombre_transporte_pto",
      "minzoom": 15,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 10,
        "visibility": "visible",
        "text-keep-upright": true
      },
      "paint": {
        "text-color": "rgba(101, 101, 101, 1)",
        "text-halo-width": 1,
        "text-halo-color": "rgba(255, 255, 255, 0.75)"
      }
    },
    {
      "id": "hidrografia_lin-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "13-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "hidrografia_lin",
      "minzoom": 13,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 13,
        "visibility": "visible",
        "text-keep-upright": true,
        "symbol-placement": "line",
        "text-justify": "center",
        "text-padding": 200,
        "text-max-angle": 45
      },
      "paint": {
        "text-color": "rgba(24, 124, 191, 1)",
        "text-halo-color": "rgba(255, 255, 255, 1)",
        "text-halo-width": 0
      }
    },
    {
      "id": "zona_verde_pol-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "13-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "zona_verde_pol",
      "minzoom": 13,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 8], [15, 10], [16, 11]]},
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "none",
        "symbol-placement": "point",
        "text-padding": 2
      },
      "paint": {
        "text-color": "rgba(109, 109, 109, 1)",
        "text-halo-width": 0.5,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "instalacion_deportiva_pol-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_deportiva_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 8], [15, 10], [18, 11]]},
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "none",
        "symbol-placement": "point",
        "text-padding": 10
      },
      "paint": {
        "text-color": "rgba(119, 125, 112, 1)",
        "text-halo-width": 0.5,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "instalacion_educativa_pol-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_educativa_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 8], [15, 10], [18, 11]]},
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "none",
        "symbol-placement": "point",
        "text-padding": 10
      },
      "paint": {
        "text-color": "rgba(128, 128, 128, 1)",
        "text-halo-width": 0.5,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "instalacion_energia_pol-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_energia_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 7], [15, 8], [18, 10]]},
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 2
      },
      "paint": {
        "text-color": "rgba(119, 125, 112, 1)",
        "text-halo-width": 0.5,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "instalacion_militar_pol-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_militar_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 8], [15, 10], [18, 11]]},
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "none",
        "symbol-placement": "point",
        "text-padding": 2
      },
      "paint": {
        "text-color": "rgba(119, 125, 112, 1)",
        "text-halo-width": 0.5,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "instalacion_sanitaria_pol-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_sanitaria_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 8], [15, 10], [18, 11]]},
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "none",
        "symbol-placement": "point",
        "text-padding": 2
      },
      "paint": {
        "text-color": "rgba(119, 125, 112, 1)",
        "text-halo-width": 0.5,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "instalacion_telecomunicacion_pol-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_telecomunicacion_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 7], [15, 8], [18, 10]]},
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 2
      },
      "paint": {
        "text-color": "rgba(119, 125, 112, 1)",
        "text-halo-width": 0.5,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "instalacion_tratamiento_aguas_pol-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_tratamiento_aguas_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 7], [15, 8], [18, 10]]},
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 2
      },
      "paint": {
        "text-color": "rgba(119, 125, 112, 1)",
        "text-halo-width": 0.5,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "instalacion_tratamiento_residuos_pol-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "instalacion_tratamiento_residuos_pol",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 7], [15, 8], [18, 10]]},
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 2
      },
      "paint": {
        "text-color": "rgba(119, 125, 112, 1)",
        "text-halo-width": 0.5,
        "text-halo-color": "rgba(255, 255, 255, 1)"
      }
    },
    {
      "id": "paso_a_nivel_pto-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "paso_a_nivel_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "icon-image": "paso_a_nivel_color",
        "icon-size": 0.5,
        "visibility": "visible"
      }
    },
    {
      "id": "paso_a_nivel_pto-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "paso_a_nivel_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 6], [15, 8], [18, 10]]},
        "visibility": "none",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 300
      },
      "paint": {"text-color": "rgba(169, 169, 169, 1)"}
    },
    {
      "id": "area_servicio_pto-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "area_servicio_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "icon-image": "area_servicio_color",
        "icon-size": 0.4,
        "visibility": "visible"
      },
      "paint": {"text-opacity": 1, "icon-opacity": 0.7}
    },
    {
      "id": "area_servicio_pto-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "area_servicio_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 6], [15, 8], [18, 10]]},
        "visibility": "none",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 300
      },
      "paint": {"text-color": "rgba(169, 169, 169, 1)"}
    },
    {
      "id": "peaje_pto-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "peaje_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "icon-image": "peaje_color",
        "icon-size": 0.5,
        "visibility": "visible"
      },
      "paint": {"text-opacity": 1, "icon-opacity": 0.6}
    },
    {
      "id": "peaje_pto-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "peaje_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 6], [15, 8], [18, 10]]},
        "visibility": "none",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 300
      },
      "paint": {"text-color": "rgba(169, 169, 169, 1)"}
    },
    {
      "id": "aparcamiento_pto-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "aparcamiento_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "icon-image": "aparcamiento_color",
        "icon-size": 0.5,
        "visibility": "visible"
      }
    },
    {
      "id": "aparcamiento_pto-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "aparcamiento_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 6], [15, 8], [18, 10]]},
        "visibility": "none",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 300
      },
      "paint": {"text-color": "rgba(169, 169, 169, 1)"}
    },
    {
      "id": "puerto_pto-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "puerto_pto",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {
        "icon-image": "puerto",
        "icon-size": 0.5,
        "visibility": "visible"
      }
    },
    {
      "id": "puerto_pto-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "puerto_pto",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 6], [15, 8], [18, 10]]},
        "visibility": "none",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 300
      },
      "paint": {"text-color": "rgba(146, 204, 243, 1)"}
    },
    {
      "id": "aerodromo_pto-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "aerodromo_pto",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {
        "icon-image": "aerodromo",
        "icon-size": 0.4,
        "visibility": "visible"
      },
      "paint": {"icon-opacity": 0.6}
    },
    {
      "id": "aerodromo_pto-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "aerodromo_pto",
      "minzoom": 12,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[10, 6], [14, 8], [18, 10]]},
        "visibility": "none",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 300
      },
      "paint": {"text-color": "rgba(133, 129, 107, 1)"}
    },
    {
      "id": "estacion_autobus_pto-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "estacion_autobus_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "icon-size": 0.4,
        "visibility": "visible",
        "icon-image": "estacion_autobus"
      },
      "paint": {"icon-opacity": 0.6}
    },
    {
      "id": "estacion_autobus_pto-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "estacion_autobus_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 6], [15, 8], [18, 10]]},
        "visibility": "none",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 300
      },
      "paint": {"text-color": "rgba(133, 129, 107, 1)"}
    },
    {
      "id": "estacion_ferrocarril_pto-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "estacion_ferrocarril_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "icon-image": "estacion_ferrocarril",
        "icon-size": 0.4,
        "visibility": "visible"
      },
      "paint": {"icon-opacity": 0.6}
    },
    {
      "id": "estacion_ferrocarril_pto-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "14-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "estacion_ferrocarril_pto",
      "minzoom": 14,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[13, 6], [15, 8], [18, 10]]},
        "visibility": "none",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "symbol-placement": "point",
        "text-padding": 300
      },
      "paint": {"text-color": "rgba(133, 129, 107, 1)"}
    },
    {
      "id": "carretera_autonomica_3er_nivel_lin-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_autonomica_3er_nivel_lin",
      "minzoom": 12,
      "maxzoom": 22,
      "filter": ["all", ["has", "ref"]],
      "layout": {
        "visibility": "visible",
        "text-field": "{ref}",
        "text-font": ["Noto Sans Regular"],
        "icon-text-fit": "both",
        "symbol-spacing": 2000,
        "symbol-placement": "line",
        "symbol-avoid-edges": false,
        "text-padding": 2,
        "text-rotation-alignment": "viewport",
        "text-pitch-alignment": "auto",
        "text-keep-upright": true,
        "icon-rotation-alignment": "viewport",
        "icon-image": "carretera_autonomica_3er_nivel_color",
        "icon-text-fit-padding": [2, 2, 2, 2],
        "text-size": 10
      },
      "paint": {
        "text-color": "rgba(0, 0, 0, 1)",
        "icon-opacity": 0.6,
        "text-opacity": 0.6
      }
    },
    {
      "id": "carretera_autonomica_2do_nivel_lin-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_autonomica_2do_nivel_lin",
      "minzoom": 12,
      "maxzoom": 22,
      "filter": ["all", ["has", "ref"]],
      "layout": {
        "visibility": "visible",
        "text-field": "{ref}",
        "text-font": ["Noto Sans Regular"],
        "icon-text-fit": "both",
        "symbol-spacing": 2000,
        "symbol-placement": "line",
        "symbol-avoid-edges": false,
        "text-padding": 2,
        "text-rotation-alignment": "viewport",
        "text-pitch-alignment": "auto",
        "text-keep-upright": true,
        "icon-rotation-alignment": "viewport",
        "icon-image": "carretera_autonomica_2do_nivel_color",
        "icon-text-fit-padding": [2, 2, 2, 2],
        "text-size": 10
      },
      "paint": {"text-color": "rgba(255, 255, 255, 1)", "icon-opacity": 0.6}
    },
    {
      "id": "carretera_autonomica_1er_nivel_lin-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "12-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_autonomica_1er_nivel_lin",
      "minzoom": 12,
      "maxzoom": 22,
      "filter": ["all", ["has", "ref"]],
      "layout": {
        "visibility": "visible",
        "text-field": "{ref}",
        "text-font": ["Noto Sans Regular"],
        "icon-text-fit": "both",
        "symbol-spacing": 2000,
        "symbol-placement": "line",
        "symbol-avoid-edges": false,
        "text-padding": 2,
        "text-rotation-alignment": "viewport",
        "text-pitch-alignment": "auto",
        "text-keep-upright": true,
        "icon-rotation-alignment": "viewport",
        "icon-image": "carretera_autonomica_1er_nivel_color",
        "icon-text-fit-padding": [2, 2, 2, 2],
        "text-size": 10
      },
      "paint": {"text-color": "rgba(0, 0, 0, 1)", "icon-opacity": 0.6}
    },
    {
      "id": "carretera_general_lin-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "11-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_general_lin",
      "minzoom": 11,
      "maxzoom": 22,
      "filter": ["all", ["has", "ref"]],
      "layout": {
        "visibility": "visible",
        "text-field": "{ref}",
        "text-font": ["Noto Sans Regular"],
        "icon-text-fit": "both",
        "symbol-spacing": 2000,
        "symbol-placement": "line",
        "symbol-avoid-edges": false,
        "text-padding": 2,
        "text-rotation-alignment": "viewport",
        "text-pitch-alignment": "auto",
        "text-keep-upright": true,
        "icon-rotation-alignment": "viewport",
        "icon-image": "carretera_general_color",
        "icon-text-fit-padding": [2, 2, 2, 2],
        "text-size": 10
      },
      "paint": {
        "text-color": "rgba(255, 255, 255, 1)",
        "text-translate-anchor": "viewport",
        "icon-opacity": 0.6
      }
    },
    {
      "id": "autopista_lin-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "10-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autopista_lin",
      "minzoom": 10,
      "maxzoom": 22,
      "filter": ["all", ["has", "ref"]],
      "layout": {
        "visibility": "visible",
        "text-field": "{ref}",
        "text-font": ["Noto Sans Regular"],
        "icon-text-fit": "both",
        "symbol-spacing": 2000,
        "symbol-placement": "line",
        "symbol-avoid-edges": false,
        "text-padding": 2,
        "text-rotation-alignment": "viewport",
        "text-pitch-alignment": "auto",
        "text-keep-upright": true,
        "icon-rotation-alignment": "viewport",
        "icon-image": "autopista_autovia_color",
        "icon-text-fit-padding": [2, 2, 2, 2],
        "text-size": 10,
        "icon-pitch-alignment": "auto"
      },
      "paint": {
        "text-color": "rgba(255, 255, 255, 1)",
        "text-translate-anchor": "map",
        "icon-translate-anchor": "map",
        "icon-opacity": 0.6
      }
    },
    {
      "id": "autovia_lin-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "10-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "autovia_lin",
      "minzoom": 10,
      "maxzoom": 22,
      "filter": ["all", ["has", "ref"]],
      "layout": {
        "visibility": "visible",
        "icon-image": "autopista_autovia_color",
        "text-field": "{ref}",
        "text-font": ["Noto Sans Regular"],
        "icon-text-fit": "both",
        "symbol-spacing": 2000,
        "symbol-placement": "line",
        "symbol-avoid-edges": false,
        "text-padding": 2,
        "text-rotation-alignment": "viewport",
        "text-pitch-alignment": "auto",
        "text-keep-upright": true,
        "icon-rotation-alignment": "viewport",
        "icon-text-fit-padding": [2, 2, 2, 2],
        "text-size": 10
      },
      "paint": {
        "text-color": "rgba(255, 255, 255, 1)",
        "text-translate-anchor": "map",
        "icon-opacity": 0.6
      }
    },
    {
      "id": "carretera_pk_pto-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "carretera_pk_pto",
      "minzoom": 15,
      "maxzoom": 22,
      "filter": ["all"],
      "layout": {
        "visibility": "visible",
        "icon-image": "carretera_pk",
        "icon-size": 0.4,
        "text-field": "{ref}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 9,
        "icon-text-fit": "none",
        "symbol-placement": "point",
        "symbol-avoid-edges": false,
        "text-padding": 2,
        "text-rotation-alignment": "auto",
        "text-pitch-alignment": "auto",
        "text-keep-upright": true,
        "icon-rotation-alignment": "auto",
        "text-offset": [0, 2]
      },
      "paint": {
        "text-color": "rgba(55, 55, 55, 1)",
        "text-halo-color": "rgba(255, 255, 255, 1)",
        "text-halo-width": 1
      }
    },
    {
      "id": "ferrocarril_pk_pto-simbolo",
      "type": "symbol",
      "metadata": {"maputnik:comment": "15-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "ferrocarril_pk_pto",
      "minzoom": 15,
      "maxzoom": 22,
      "filter": ["all"],
      "layout": {
        "visibility": "visible",
        "icon-image": "ferrocarril_pk",
        "icon-size": 0.4,
        "text-field": "{ref}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 9,
        "icon-text-fit": "none",
        "symbol-placement": "point",
        "symbol-avoid-edges": false,
        "text-padding": 2,
        "text-rotation-alignment": "auto",
        "text-pitch-alignment": "auto",
        "text-keep-upright": true,
        "icon-rotation-alignment": "auto"
      },
      "paint": {
        "text-color": "rgba(55, 55, 55, 1)",
        "text-halo-color": "rgba(255, 255, 255, 1)",
        "text-halo-width": 1
      }
    },
    {
      "id": "altimetria_pto",
      "type": "circle",
      "metadata": {"maputnik:comment": "17-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "altimetria_pto",
      "minzoom": 17,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "circle-color": "rgba(224, 111, 0, 1)",
        "circle-radius": 2,
        "circle-pitch-alignment": "viewport"
      }
    },
    {
      "id": "altimetria_pto-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "17-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "altimetria_pto",
      "minzoom": 17,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{altitud}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 8,
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "text-offset": [0, -1],
        "symbol-placement": "point"
      },
      "paint": {"text-color": "rgba(224, 111, 0, 1)"}
    },
    {
      "id": "portal_pto",
      "type": "circle",
      "metadata": {"maputnik:comment": "18-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "portal_pto",
      "minzoom": 18,
      "maxzoom": 22,
      "layout": {"visibility": "visible"},
      "paint": {
        "circle-color": "rgba(45, 45, 45, 1)",
        "circle-radius": 2,
        "circle-pitch-alignment": "viewport"
      }
    },
    {
      "id": "portal_pto-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "18-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "portal_pto",
      "minzoom": 18,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{ref}",
        "text-font": ["Noto Sans Regular"],
        "text-size": 9,
        "visibility": "visible",
        "text-keep-upright": true,
        "text-transform": "uppercase",
        "text-offset": [0, -1]
      },
      "paint": {
        "text-color": "rgba(45, 45, 45, 1)",
        "text-halo-color": "rgba(255, 255, 255, 1)",
        "text-halo-width": 1
      }
    },
    {
      "id": "via_urbana_lin-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "16-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "via_urbana_lin",
      "minzoom": 16,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Regular"],
        "text-size": {"stops": [[16, 9], [18, 11]]},
        "visibility": "visible",
        "text-keep-upright": true,
        "symbol-placement": "line",
        "text-justify": "center",
        "text-padding": {"stops": [[16, 8], [18, 10]]},
        "text-max-angle": 45
      },
      "paint": {
        "text-color": "rgba(86, 86, 86, 1)",
        "text-halo-color": "rgba(255, 255, 255, 1)",
        "text-halo-width": 1
      }
    },
    {
      "id": "espacio_natural_protegido_pol-texto",
      "type": "symbol",
      "metadata": {"maputnik:comment": "9-22"},
      "source": "VTS_MapaBaseRioja_SCN",
      "source-layer": "espacio_natural_protegido_pol",
      "minzoom": 7,
      "maxzoom": 22,
      "layout": {
        "text-anchor": "center",
        "text-field": "{nombre}",
        "text-font": ["Noto Sans Italic"],
        "text-size": 12,
        "visibility": "visible",
        "text-keep-upright": true,
        "text-padding": {"stops": [[9, 170], [10, 120], [11, 50]]}
      },
      "paint": {
        "text-color": "rgba(111, 154, 133, 1)",
        "text-halo-color": "rgba(255, 255, 255, 0.75)",
        "text-halo-width": 2
      }
    }
  ],
  "id": "w057wntj3",
  "owner": "Gobierno de La Rioja"
}